### ISSUE TITLE
Grades for 'YAML Yodeller' (week 12)

### ISSUE THREAD

**Issue by akhoinguyen** [akhoinguyen/ecommerce-pattern-library#12]
<img width="1425" alt="Screen Shot 2020-04-14 at 12 14 47 AM" src="https://user-images.githubusercontent.com/43136539/79612895-81a4d080-80cb-11ea-8ced-dd3ad2485dfb.png">

@thomasjbradley

**Comment by thomasjbradley** [comment]
🌈
