### ISSUE TITLE
Final Grade - it's been a journey...

### ISSUE THREAD

**Issue by akhoinguyen** [akhoinguyen/ecommerce-pattern-library#17]
Hi @thomasjbradley

It's been fun working on this project and seeing the website come together from just sketches and mock-ups. I got to experiment a lot with styles, animations, transitions and all of those combined with ***gasp*** javascript to add a little more fun to the website and I'm really glad it helped me learned a lot. Thank you for being patient with all of us even though at one point it might fell like giving up.

I've completed my pattern library and I think overall it looks great. Though I might be missing couple of things here and there but overall I've achieved about 95% what I planned. I got the look and feel of the website to be what I wanted and I'm proud I could do that with what I've been learning for the last 4 terms.

---
*Style & Design* - **3**
The website successfully achieve the look and feel of an art-related e-comm website: modern with a touch of decorative elements that don't overwhelm the main focus: the artworks. All at the same time the patterns are cohesive with a clean and modern design. Transitions and animations are moderately used to add interest with careful considerations to not become distracting.

*Patterns* - **3**
All patterns created were able to built the entire site with functional pages. Patterns are well incorporated into one another, include features are optimally utilized & no extra CSS files needed.

*Explanation* - **3**
Clear explanation with detailed instructions on where and when to use which instances of each pattern and warnings on when *not* to use some.

*Accessibility* - **1.5**
Aside from skip links, WAI_ARIA roles and properly save-for-web images, not much attention has been paid to accessibility. Some improvements include: adding `alt` attribute to `img` tags, text size on small screens, tex-background contrast, more obvious links.

*Semantics* - **3**
Great use of HTML tags and attributes with correct use.

*Responsiveness* - **3**
Great responsiveness was achieved by extensive use of grid system. Images resize properly, text and other elements display nicely without any awkwardness.

*Code quality* - **3**
Excellent code quality, great & appropriate use of code in HTML, CSS and JS files.

*Git & Commits* - **2.5**
Overall good commits. Longer commits are written in full details; shorter commits are for minor tweaks and could be combined.

---
22/24 - **91.6%**

**Comment by thomasjbradley** [comment]
Amazing work—your website truly looks like a large-scale ecommerce website! Thank you for putting in lots of effort to learn & apply the material this term.
