### ISSUE TITLE
Marks for 'Sharing code with layouts' (week 9)

### ISSUE THREAD

**Issue by akhoinguyen** [akhoinguyen/ecommerce-pattern-library#2]
Hi @thomasjbradley,

I've completed the assignment 'Sharing code with layouts' from week 9, please have a look.
Thank you,
Khoi

**Comment by thomasjbradley** [comment]
:godmode:

**Comment by thomasjbradley** [comment]
(Hopefully you’re a Doom fan!)

**Comment by akhoinguyen** [comment]
I'm not, cool looking dude tho!
