### ISSUE TITLE
Grades for 'Selector Surgeon' (week 10)

### ISSUE THREAD

**Issue by akhoinguyen** [akhoinguyen/ecommerce-pattern-library#3]
@thomasjbradley tadaa!
<img width="1419" alt="Screen Shot 2020-03-23 at 10 41 35 PM" src="https://user-images.githubusercontent.com/43136539/77569899-50a4f780-6ea1-11ea-85f9-42de926d844e.png">

**Comment by thomasjbradley** [comment]
✨
