### ISSUE TITLE
Grades for 'Markdown Manipulator' (week 11)

### ISSUE THREAD

**Issue by akhoinguyen** [akhoinguyen/ecommerce-pattern-library#9]
@thomasjbradley yee
<img width="1425" alt="Screen Shot 2020-04-02 at 11 28 08 PM" src="https://user-images.githubusercontent.com/43136539/78321357-b7797f00-7539-11ea-9cfc-ba095d5b3c1e.png">

**Comment by thomasjbradley** [comment]
:boom:
